### ISSUE TITLE
Suggestion: Soundcloud functionality

### ISSUE THREAD

**Issue by FFZendikar** [meew0/Lethe#47] opened 2016-01-12 20:44 UTC
As stated in the title; not sure how difficult it would be to implement however.

**Comment by Sikksens** [comment] 2016-01-12 20:48
meew0 has planned to implement it here #24

**Comment by meew0** [comment] 2016-01-12 20:50
As said already, this is a duplicate of #24. I'm working on it locally, but there's no ETA

**Closed as completed by meew0** 2016-01-12 20:50 UTC
Labels: duplicate
